version: '3.8'

services:
  portfolio:
    image: nginx:alpine
    container_name: iPortfolio
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
